dbServer:
  hostPort: "192.168.1.232:5050"
serve:
  hostPort: ":5022"
rabbitmq:
  hostPort: "192.168.1.232:30418"
  username: "websocket"
  password: "cl87654321!"
  vHost: "generator-backend"
  prefetch: 30
  exchanges:
    - name: "websocketServer-direct"
      kind: "direct"
  queuePrefix: "websocketServer"
oss:
  endPoint: "https://oss-cn-shenzhen.aliyuncs.com"
  accessKeyID: "LTAIoh5uIkAzSN25"
  accessKeySecret: "3XZO16LsLVx7V1JEBT6PnozzvhH4Xx"
  bucketName: "signposs1"
common:
  connectTimeout: 10
  staticPath: static
