// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto5g

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusReply struct {
	WebsocketConnections uint32   `protobuf:"varint,1,opt,name=websocketConnections,proto3" json:"websocketConnections,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (m *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(m, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetWebsocketConnections() uint32 {
	if m != nil {
		return m.WebsocketConnections
	}
	return 0
}

type WebsocketClientLoginRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebsocketClientLoginRequest) Reset()         { *m = WebsocketClientLoginRequest{} }
func (m *WebsocketClientLoginRequest) String() string { return proto.CompactTextString(m) }
func (*WebsocketClientLoginRequest) ProtoMessage()    {}
func (*WebsocketClientLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *WebsocketClientLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebsocketClientLoginRequest.Unmarshal(m, b)
}
func (m *WebsocketClientLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebsocketClientLoginRequest.Marshal(b, m, deterministic)
}
func (m *WebsocketClientLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsocketClientLoginRequest.Merge(m, src)
}
func (m *WebsocketClientLoginRequest) XXX_Size() int {
	return xxx_messageInfo_WebsocketClientLoginRequest.Size(m)
}
func (m *WebsocketClientLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsocketClientLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebsocketClientLoginRequest proto.InternalMessageInfo

func (m *WebsocketClientLoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type WebsocketClientLoginReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebsocketClientLoginReply) Reset()         { *m = WebsocketClientLoginReply{} }
func (m *WebsocketClientLoginReply) String() string { return proto.CompactTextString(m) }
func (*WebsocketClientLoginReply) ProtoMessage()    {}
func (*WebsocketClientLoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *WebsocketClientLoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebsocketClientLoginReply.Unmarshal(m, b)
}
func (m *WebsocketClientLoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebsocketClientLoginReply.Marshal(b, m, deterministic)
}
func (m *WebsocketClientLoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsocketClientLoginReply.Merge(m, src)
}
func (m *WebsocketClientLoginReply) XXX_Size() int {
	return xxx_messageInfo_WebsocketClientLoginReply.Size(m)
}
func (m *WebsocketClientLoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsocketClientLoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_WebsocketClientLoginReply proto.InternalMessageInfo

func (m *WebsocketClientLoginReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "proto5g.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "proto5g.StatusReply")
	proto.RegisterType((*WebsocketClientLoginRequest)(nil), "proto5g.WebsocketClientLoginRequest")
	proto.RegisterType((*WebsocketClientLoginReply)(nil), "proto5g.WebsocketClientLoginReply")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xd9, 0x15, 0x2b, 0x1d, 0xad, 0x42, 0x28, 0xa2, 0x6b, 0x41, 0x59, 0x3c, 0x08, 0xd2,
	0x0d, 0x56, 0xf4, 0xe2, 0xa9, 0xf5, 0x26, 0x1e, 0x64, 0x3d, 0xe8, 0xd1, 0x6c, 0x1b, 0x63, 0xe8,
	0x36, 0x13, 0x9b, 0xd9, 0x96, 0x5e, 0x7d, 0x05, 0x1f, 0xc5, 0x47, 0xf1, 0x01, 0x04, 0xf1, 0x41,
	0xa4, 0xd9, 0x5a, 0x14, 0x8b, 0x9e, 0x32, 0xf3, 0xcf, 0xf7, 0x67, 0x86, 0x1f, 0xaa, 0xc2, 0xea,
	0xc4, 0x0e, 0x91, 0x90, 0xad, 0xf8, 0xe7, 0x44, 0x45, 0x0d, 0x85, 0xa8, 0x72, 0xc9, 0x85, 0xd5,
	0x5c, 0x18, 0x83, 0x24, 0x48, 0xa3, 0x71, 0x25, 0x16, 0x35, 0x95, 0xa6, 0x87, 0x22, 0x4b, 0xba,
	0x38, 0xe0, 0x0a, 0x15, 0x72, 0x2f, 0x67, 0xc5, 0xbd, 0xef, 0x7c, 0xe3, 0xab, 0x19, 0x7e, 0xfa,
	0x0d, 0x1f, 0x8c, 0x35, 0xf5, 0x71, 0xcc, 0x15, 0x36, 0xfd, 0xb0, 0x39, 0x12, 0xb9, 0xee, 0x09,
	0xc2, 0xa1, 0xe3, 0xf3, 0xb2, 0xf4, 0xc5, 0x1b, 0x50, 0xbb, 0x26, 0x41, 0x85, 0x4b, 0xe5, 0x63,
	0x21, 0x1d, 0xc5, 0x6d, 0x58, 0xfd, 0x12, 0x6c, 0x3e, 0x61, 0x2d, 0xa8, 0x8f, 0x65, 0xe6, 0xb0,
	0xdb, 0x97, 0x74, 0x8e, 0xc6, 0xc8, 0xae, 0x3f, 0x72, 0x2b, 0xd8, 0x0b, 0x0e, 0x6a, 0xe9, 0xc2,
	0x59, 0x7c, 0x06, 0x3b, 0x37, 0x73, 0x3d, 0xd7, 0xd2, 0xd0, 0x25, 0x2a, 0x6d, 0x66, 0x1b, 0x58,
	0x03, 0x96, 0x09, 0xfb, 0xd2, 0xf8, 0x3f, 0xaa, 0x9d, 0xca, 0xfb, 0xdb, 0x6e, 0x78, 0x1b, 0xa4,
	0xa5, 0x18, 0x1f, 0xc2, 0xf6, 0x62, 0xf3, 0xf4, 0x9a, 0x75, 0x08, 0x75, 0xaf, 0xf4, 0xa5, 0xa1,
	0xee, 0xb5, 0x5e, 0x02, 0x58, 0x6a, 0x5b, 0xcd, 0xee, 0xa0, 0xbe, 0xc8, 0xc4, 0xf6, 0x93, 0x59,
	0xd8, 0xc9, 0x1f, 0x07, 0x45, 0xf1, 0x3f, 0xd4, 0x74, 0xf3, 0x05, 0x54, 0xca, 0x58, 0xd8, 0xe6,
	0x9c, 0xfe, 0x11, 0x5c, 0x54, 0xff, 0xa5, 0xdb, 0x7c, 0x12, 0xb3, 0xa7, 0xd7, 0x8f, 0xe7, 0x70,
	0x8d, 0x01, 0x1f, 0x1d, 0x71, 0xe7, 0x07, 0x9d, 0xf0, 0x2a, 0xc8, 0x2a, 0x1e, 0x3e, 0xfe, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0x2d, 0xc8, 0x95, 0xe6, 0x19, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	WebsocketClientLogin(ctx context.Context, in *WebsocketClientLoginRequest, opts ...grpc.CallOption) (*WebsocketClientLoginReply, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) WebsocketClientLogin(ctx context.Context, in *WebsocketClientLoginRequest, opts ...grpc.CallOption) (*WebsocketClientLoginReply, error) {
	out := new(WebsocketClientLoginReply)
	err := c.cc.Invoke(ctx, "/proto5g.Api/WebsocketClientLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/proto5g.Api/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	WebsocketClientLogin(context.Context, *WebsocketClientLoginRequest) (*WebsocketClientLoginReply, error)
	Status(context.Context, *StatusRequest) (*StatusReply, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) WebsocketClientLogin(ctx context.Context, req *WebsocketClientLoginRequest) (*WebsocketClientLoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebsocketClientLogin not implemented")
}
func (*UnimplementedApiServer) Status(ctx context.Context, req *StatusRequest) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_WebsocketClientLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebsocketClientLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).WebsocketClientLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto5g.Api/WebsocketClientLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).WebsocketClientLogin(ctx, req.(*WebsocketClientLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto5g.Api/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto5g.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WebsocketClientLogin",
			Handler:    _Api_WebsocketClientLogin_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Api_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
